version: "3.9"
services:
  running_page:
    container_name: running_page
    image: running_page:latest
    build:
      context: .
      labels:
        com.centurylinklabs.watchtower.enable: false
    restart: unless-stopped
    command: bash -c "while true; do echo hello; sleep 2; done"
    volumes:
      - ./GPX_OUT:/root/running_page/GPX_OUT
      - ./TCX_OUT:/root/running_page/TCX_OUT
      - ./scripts:/root/running_page/scripts
